name: "LogChimp"

services:
  cache:
    image: valkey/valkey:8
    expose:
      - "6379"
    command: [ "valkey-server", "--save", "60", "1", "--loglevel", "warning", "--dir", "/data" ]
    volumes:
      - valkey-data:/data
    networks:
      - logchimp

  db:
    image: postgres:12
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-logchimp}
      POSTGRES_USER: ${POSTGRES_USER:-logchimp}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-logchimp} -d ${POSTGRES_DB:-logchimp}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - logchimp

  api:
    image: ghcr.io/logchimp/logchimp/api:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
    environment:
      NODE_ENV: production
      PORT: ${API_PORT:-8080}
      LOGCHIMP_API_HOST: ${LOGCHIMP_API_HOST:-0.0.0.0}
      LOGCHIMP_IS_SELF_HOSTED: true
      LOGCHIMP_SECRET_KEY: ${LOGCHIMP_SECRET_KEY:-changeme}
      LOGCHIMP_MACHINE_SIGNATURE: ${LOGCHIMP_MACHINE_SIGNATURE:-changeme}
      LOGCHIMP_WEB_URL: ${LOGCHIMP_WEB_URL:-http://localhost:8080}

      # Database
      LOGCHIMP_DB_HOST: db
      LOGCHIMP_DB_DATABASE: ${POSTGRES_DB:-logchimp}
      LOGCHIMP_DB_PORT: 5432
      LOGCHIMP_DB_USER: ${POSTGRES_USER:-logchimp}
      LOGCHIMP_DB_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      LOGCHIMP_DB_SSL: ${LOGCHIMP_DB_SSL:-false}

      # Cache
      LOGCHIMP_VALKEY_URL: cache:6379

      # Mail
      LOGCHIMP_MAIL_HOST: ${LOGCHIMP_MAIL_HOST:-}
      LOGCHIMP_MAIL_USER: ${LOGCHIMP_MAIL_USER:-}
      LOGCHIMP_MAIL_PASSWORD: ${LOGCHIMP_MAIL_PASSWORD:-}
      LOGCHIMP_MAIL_PORT: ${LOGCHIMP_MAIL_PORT:-}
    ports:
      - "${API_PORT:-8080}:${API_PORT:-8080}"
    networks:
      - logchimp

  theme:
    image: ghcr.io/logchimp/logchimp/theme:latest
    restart: unless-stopped
    depends_on:
      - api
    environment:
      NODE_ENV: production
      PORT: ${THEME_PORT:-3000}
      VITE_API_URL: ${LOGCHIMP_API_URL:-http://localhost:8080}
      VITE_IS_SELF_HOSTED: true
    ports:
      - "${THEME_PORT:-3000}:${THEME_PORT:-3000}"
    networks:
      - logchimp

networks:
  logchimp:
    driver: bridge

volumes:
  valkey-data:
  postgres:
